covid19repo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('repo.urls')),
    path('admin/', admin.site.urls),
]

repo/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls

from . import views

app_name = 'repo'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('database', views.DatabaseView.as_view(), name='database'),
    path('collections', views.CollectionsView.as_view(), name='collections'),
    path('collections/create', views.create_collection, name='collections_create'),
    path('collections/<int:pk>/details',
         views.CollectionDetailsView.as_view(), name='collection_details'),
    path('collections/<int:pk>/delete',
         views.CollectionDeleteView.as_view(), name='collection_delete'),
    path('collections/<int:collection_id>/<int:sequence_id>/delete',
         views.collection_sequence_delete, name='collection_sequence_delete'),
    path('collections/<int:collection_id>/add',
         views.add_to_collection, name='add_to_collection'),
    path('collections/<int:collection_id>/download_pdf',
         views.download_collection_pdf, name='download_pdf'),
    path('stats', views.stats, name='stats'),

    path('accounts/', include('django.contrib.auth.urls'))
]

repo/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Taxonomy(models.Model):
    name = models.CharField('name', max_length=200)
    value = models.CharField('value', max_length=200)
    count = models.IntegerField('count')

    def __str__(self):
        return self.name

class Center(models.Model):
    name = models.CharField('name', max_length=200)
    value = models.CharField('value', max_length=200)
    count = models.IntegerField('count')

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField('name', max_length=200)
    value = models.CharField('value', max_length=200)
    count = models.IntegerField('count')

    def __str__(self):
        return self.name

class ViralSequence(models.Model):
    accession = models.CharField('accession', max_length=200, unique=True)
    center = models.ForeignKey(Center, null=True, on_delete=models.DO_NOTHING)
    country = models.ForeignKey(Country, null=True, on_delete=models.DO_NOTHING)
    taxonomy = models.ForeignKey(Taxonomy, null=True, on_delete=models.DO_NOTHING)
    collection_date = models.DateField('collection date')    
    host = models.CharField('host', max_length=200)
    isolate = models.CharField('isolate', max_length=200)

    def __str__(self):
        return self.accession

class Collection(models.Model):
    owner = ForeignKey(User, on_delete=models.DO_NOTHING)
    sequences = ManyToManyField(ViralSequence)
    name = models.CharField('name', max_length=200)
    creation_date = models.DateTimeField('creation_date', default=timezone.now)

    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField('name', max_length=200)
    email = models.EmailField('email', max_length=200)
    phone_number = models.CharField('phone_number', max_length=200)
    address = models.CharField('address', max_length=200)

    def __str__(self):
        return self.name

repo/views.py
import time
from django.contrib import messages
from django.contrib.auth.views import redirect_to_login
from django.core.files.storage import FileSystemStorage
from django.http.response import FileResponse, HttpResponse, HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from weasyprint import HTML
import json

from .models import Center, ViralSequence, Collection

# Helper functions
from .views_helpers import *


class IndexView(generic.ListView):
    model = ViralSequence
    template_name = 'repo/home.html'
    context_object_name = "sequences"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_obj'] = ViralSequence.objects.order_by(
            '-collection_date')[:5]
        if self.request.user.is_authenticated:
            context['collections'] = Collection.objects.filter(
                owner=self.request.user).order_by('-creation_date')[:5]
        return context


class DatabaseView(generic.ListView):
    paginate_by = 20
    model = ViralSequence
    template_name = 'repo/database.html'

    def get_queryset(self):
        return get_table_queryset(self.request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return get_table_context_data(context)


class CollectionsView(LoginRequiredMixin, generic.ListView):
    model = Collection
    template_name = 'repo/collections.html'
    context_object_name = 'collections'

    login_url = '/accounts/login/'

    def get_queryset(self):
        user = self.request.user
        return Collection.objects.filter(owner=user)


@login_required()
def create_collection(request):
    sequences = get_table_queryset(request)
    context = get_paginated_context(request, sequences)

    if request.method == 'POST':
        if 'create' in request.POST:
            if 'collection_name' in request.POST and request.POST['collection_name'].strip() != '':
                collection = Collection()
                collection.owner = request.user
                collection.name = request.POST.get('collection_name')
                collection.save()
                if (request.POST.get('hidden_choice') != '' and request.POST.get('hidden_choice') != None):
                    choices = request.POST.get('hidden_choice')
                    choices = [int(choice) for choice in choices.split(',')]
                    collection.sequences.add(*choices)
                return HttpResponseRedirect(reverse('repo:collection_details', args=(collection.pk,)))
            else:
                messages.add_message(
                    request, messages.ERROR, 'You have to name your collection before submiting')
                return render(request, 'repo/collections/create.html', context)

    return render(request, 'repo/collections/create.html', context)


@login_required()
def add_to_collection(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)

    sequences = get_table_queryset(request)
    col_seq = collection.sequences.all()
    sequences = sequences.difference(col_seq)
    context = get_paginated_context(request, sequences)

    if request.method == 'POST':
        if 'add' in request.POST:
            if (request.POST.get('hidden_choice') != '' and request.POST.get('hidden_choice') != None):
                choices = request.POST.get('hidden_choice')
                choices = [int(choice) for choice in choices.split(',')]
                collection.sequences.add(*choices)
            return HttpResponseRedirect(reverse('repo:collection_details', args=(collection.pk,)))

    return render(request, 'repo/collections/add.html', context)


class CollectionDetailsView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Collection
    template_name = 'repo/collections/details.html'
    context_object_name = 'collection'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        name = request.POST.get('name')
        if name:
            self.object.name = name
            self.object.save()

        return self.render_to_response(self.get_context_data(**kwargs))

    def get_context_data(self, **kwargs):
        context = super(CollectionDetailsView, self).get_context_data(**kwargs)
        context = get_table_context_data(context)
        sequences = self.get_object().sequences.all()
        order, filters = get_table_filters(self.request)
        filtered = sequences.filter(**filters).order_by(order)
        paginator = Paginator(filtered, 20)
        page = self.request.GET.get('page')
        context['page_obj'] = paginator.get_page(page)
        return context

    def test_func(self):
        return self.request.user == self.get_object().owner

    def handle_no_permission(self):
        return redirect_to_login(self.request.GET.get('next', self.request.POST.get('next', reverse('repo:collection_details', args=(self.get_object().pk,)))))


class CollectionDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Collection
    success_url = reverse_lazy('repo:collections')
    template_name = 'repo/confirm_delete.html'

    def test_func(self):
        return self.request.user == self.get_object().owner

    def handle_no_permission(self):
        return redirect_to_login(self.request.GET.get('next', self.request.POST.get('next', reverse('repo:collection_delete', args=(self.get_object().pk,)))))


@login_required()
def collection_sequence_delete(request, collection_id, sequence_id):
    sequence = get_object_or_404(ViralSequence, pk=sequence_id)
    collection = get_object_or_404(Collection, pk=collection_id)

    if request.user != collection.owner:
        return redirect_to_login(request.GET.get('next', request.POST.get('next', reverse('repo:collection_sequence_delete', args=(collection.pk, sequence.pk)))))

    if request.method == 'POST':
        collection.sequences.remove(sequence)
        return HttpResponseRedirect(reverse('repo:collection_details', args=(collection_id,)))

    return render(request, 'repo/confirm_delete.html', context={'object': sequence, 'seq_collection': collection})


@login_required()
def download_collection_pdf(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)

    if request.user != collection.owner:
        return redirect_to_login(request.GET.get('next', request.POST.get('next', reverse('repo:download_pdf', args=(collection.pk, )))))

    html_string = render_to_string(
        'repo/collections/pdf.html', {'page_obj': collection.sequences.all()})

    html = HTML(string=html_string)
    html.write_pdf(target='/tmp/' + str(collection.name) + '.pdf')

    fs = FileSystemStorage('/tmp')
    with fs.open(str(collection.name) + '.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="' + \
            str(collection.name) + '.pdf"'
        return response

    return HttpResponseRedirect(reverse('repo:collection_details', args=(collection_id,)))


def stats(request):
    country_names = []
    country_count = []
    center_names = []
    center_count = []

    for country in Country.objects.all():
        country_names.append(country.name)
        country_count.append(country.count)

    for center in Center.objects.all():
        center_names.append(center.name)
        center_count.append(center.count)

    context = {
        'country_names': json.dumps(country_names),
        'country_count': json.dumps(country_count),
        'center_names': json.dumps(center_names),
        'center_count': json.dumps(center_count)
    }

    return render(request, 'repo/stats.html', context)

repo/templates/repo/base.html
{% load static %}

<head>
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
        crossorigin="anonymous">
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <script
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js">
    </script>

    {% block head %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
        <div class="container">
            <a class="navbar-brand" href="{% url 'repo:home' %}">Covid-19
                repo</a>
            <div class="collapse navbar-collapse justify-content-between">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link"
                        href="{% url 'repo:home' %}">Home</a>
                    <a class="nav-item nav-link"
                        href="{% url 'repo:database' %}">Database</a>
                    <a class="nav-item nav-link"
                        href="{% url 'repo:stats' %}">Stats</a>
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link"
                        href="{% url 'repo:collections' %}">Collections</a>
                    {% endif %}
                </div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <span class="navbar-text">Logged in as:
                        {{ user.username }}</span>
                    <a class="nav-item nav-link"
                        href="{% url 'repo:logout' %}">Sign out</a>
                    {% else %}
                    <a class="nav-item nav-link"
                        href="{% url 'repo:login' %}">Sign in</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <div style="min-height:70vh;">
            {% for message in messages %}
            <div class="alert {{ message.tags }}" role="alert">{{ message }}</div>
            {% endfor %}
            {% block content %}
            {% endblock %}
        </div>
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col">

                </div>
                <div class="col">

                </div>
                <div class="col">
                    <h5>Contact Us</h5>
                    <ul class="list-unstyled text-small text-muted">
                        <li>E-mail: <a class="text-muted text-decoration-none"
                                href="mailto:{{ EMAIL }}">{{ EMAIL }}</a></li>
                        <li>Phone number: {{ PHONE_NUMBER }}</li>
                        <li>Address: {{ ADDRESS }}</li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

</body>

repo/templates/repo/collections.html
{% extends "repo/base.html" %}

{% block head %}
<title>Collections</title>
{% endblock %}

{% block content %}
{% if collections %}
{% include 'repo/collections/collections_table.html' %}
{% else %}
No collections created!<br>
{% endif %}
<a class="btn btn-primary mb-2"
    href="{% url 'repo:collections_create' %}">Create new collection</a>
{% endblock %}

repo/templates/repo/confirm_delete.html
{% extends 'repo/base.html' %}

{% block head %}
<title>Confirm deletion</title>
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"{% if seq_collection %} from "{{ seq_collection }}"{% endif %}?</p>
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>
{% endblock %}

repo/templates/repo/database.html
{% extends "repo/base.html" %}

{% block head %}
<title>Database</title>
{% endblock %}

{% block content %}
{% include "repo/table/body.html" %}
{% include "repo/table/navigation.html" %}
{% include "repo/table/filters.html" %}
{% endblock %}

repo/templates/repo/home.html
{% extends "repo/base.html" %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block content %}
<p class="lead mt-2">Currently {{ sequences.count }} sequences in database.</p>

<div class="mt-4">
    <h1 class="lead mt-2">Recently added sequences</h1>
    {% include "repo/table/body_clean.html" %}
    {% if user.is_authenticated %}
    <h1 class="lead mt-4">Your recent collections</h1>
    {% include 'repo/collections/collections_table.html' %}
    {% endif %}
</div>

{% endblock %}

repo/templates/repo/stats.html
{% extends 'repo/base.html' %}

{% block head %}
<title>Stats</title>

<script src="https://cdn.jsdelivr.net/npm/chart.js@3.2.1/dist/chart.min.js"
    integrity="sha256-uVEHWRIr846/vAdLJeybWxjPNStREzOlqLMXjW/Saeo="
    crossorigin="anonymous"></script>

<script>

    function getRandomColor() {
        var letters = '0123456789ABCDEF'.split('');
        var color = '#';
        for (var i = 0; i < 6; i++ ) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

    function getColors(model) {
        var colors = []
        for (var i = 0; i < model.length; i++) {
            colors.push(getRandomColor())
        }
        return colors
    }

    const config_country = {
        type: 'doughnut',
        data: {
            datasets: [{
                data: {{ country_count|safe }},
                backgroundColor: getColors({{ country_count|safe }})           
            }],
            labels: {{ country_names|safe }}
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: 'Sequence count by country'
                }
            }
        }
    };

    const config_center = {
        type: 'doughnut',
        data: {
            datasets: [{
                data: {{ center_count|safe }},
                backgroundColor: getColors({{ center_count|safe }})
            }],
            labels: {{ center_names|safe }}
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: 'Sequence count by center'
                }
            }
        }
    };

    window.onload = function () {
        var countryCTX = document.getElementById('countryChart')
            .getContext('2d');
        var centerCTX = document.getElementById('countryChart')
            .getContext('2d');
        window.countryChart = new Chart(countryChart, config_country);
        window.centerChart = new Chart(centerChart, config_center);
    };
</script>
{% endblock %}

{% block content %}
<div class="d-flex flex-row" style="height: 750px;">
    <div class="chart-container" style="position: relative; height:50vh; width:100vw">
        <canvas id="countryChart"></canvas>
    </div>
    <div class="chart-container" style="position: relative; height:50vh; width:100vw">
        <canvas id="centerChart"></canvas>
    </div>
</div>
{% endblock %}