covid19repo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('repo.urls')),
    path('admin/', admin.site.urls),
]

repo/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls

from . import views

app_name = 'repo'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('database', views.DatabaseView.as_view(), name='database'),
    path('collections', views.CollectionsView.as_view(), name='collections'),
    path('collections/create', views.create_collection, name='collections_create'),
    path('collections/<int:pk>/details',
         views.CollectionDetailsView.as_view(), name='collection_details'),
    path('collections/<int:pk>/delete',
         views.CollectionDeleteView.as_view(), name='collection_delete'),
    path('collections/<int:collection_id>/<int:sequence_id>/delete',
         views.collection_sequence_delete, name='collection_sequence_delete'),
    path('collections/<int:collection_id>/add',
         views.add_to_collection, name='add_to_collection'),
    path('collections/<int:collection_id>/download_pdf',
         views.download_collection_pdf, name='download_pdf'),
    path('stats', views.stats, name='stats'),

    path('accounts/', include('django.contrib.auth.urls'))
]

repo/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey, ManyToManyField
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Taxonomy(models.Model):
    name = models.CharField('name', max_length=200)
    value = models.CharField('value', max_length=200)
    count = models.IntegerField('count')

    def __str__(self):
        return self.name

class Center(models.Model):
    name = models.CharField('name', max_length=200)
    value = models.CharField('value', max_length=200)
    count = models.IntegerField('count')

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField('name', max_length=200)
    value = models.CharField('value', max_length=200)
    count = models.IntegerField('count')

    def __str__(self):
        return self.name

class ViralSequence(models.Model):
    accession = models.CharField('accession', max_length=200, unique=True)
    center = models.ForeignKey(Center, null=True, on_delete=models.DO_NOTHING)
    country = models.ForeignKey(Country, null=True, on_delete=models.DO_NOTHING)
    taxonomy = models.ForeignKey(Taxonomy, null=True, on_delete=models.DO_NOTHING)
    collection_date = models.DateField('collection date')    
    host = models.CharField('host', max_length=200)
    isolate = models.CharField('isolate', max_length=200)

    def __str__(self):
        return self.accession

class Collection(models.Model):
    owner = ForeignKey(User, on_delete=models.DO_NOTHING)
    sequences = ManyToManyField(ViralSequence)
    name = models.CharField('name', max_length=200)
    creation_date = models.DateTimeField('creation_date', default=timezone.now)

    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField('name', max_length=200)
    email = models.EmailField('email', max_length=200)
    phone_number = models.CharField('phone_number', max_length=200)
    address = models.CharField('address', max_length=200)

    def __str__(self):
        return self.name

repo/views.py
import time
from django.contrib import messages
from django.contrib.auth.views import redirect_to_login
from django.core.files.storage import FileSystemStorage
from django.http.response import FileResponse, HttpResponse, HttpResponseRedirect
from django.urls.base import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from weasyprint import HTML
import json

from .models import Center, ViralSequence, Collection

# Helper functions
from .views_helpers import *


class IndexView(generic.ListView):
    model = ViralSequence
    template_name = 'repo/home.html'
    context_object_name = "sequences"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_obj'] = ViralSequence.objects.order_by(
            '-collection_date')[:5]
        if self.request.user.is_authenticated:
            context['collections'] = Collection.objects.filter(
                owner=self.request.user).order_by('-creation_date')[:5]
        return context


class DatabaseView(generic.ListView):
    paginate_by = 20
    model = ViralSequence
    template_name = 'repo/database.html'

    def get_queryset(self):
        return get_table_queryset(self.request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return get_table_context_data(context)


class CollectionsView(LoginRequiredMixin, generic.ListView):
    model = Collection
    template_name = 'repo/collections.html'
    context_object_name = 'collections'

    login_url = '/accounts/login/'

    def get_queryset(self):
        user = self.request.user
        return Collection.objects.filter(owner=user)


@login_required()
def create_collection(request):
    sequences = get_table_queryset(request)
    context = get_paginated_context(request, sequences)

    if request.method == 'POST':
        if 'create' in request.POST:
            if 'collection_name' in request.POST and request.POST['collection_name'].strip() != '':
                collection = Collection()
                collection.owner = request.user
                collection.name = request.POST.get('collection_name')
                collection.save()
                if (request.POST.get('hidden_choice') != '' and request.POST.get('hidden_choice') != None):
                    choices = request.POST.get('hidden_choice')
                    choices = [int(choice) for choice in choices.split(',')]
                    collection.sequences.add(*choices)
                return HttpResponseRedirect(reverse('repo:collection_details', args=(collection.pk,)))
            else:
                messages.add_message(
                    request, messages.ERROR, 'You have to name your collection before submiting')
                return render(request, 'repo/collections/create.html', context)

    return render(request, 'repo/collections/create.html', context)


@login_required()
def add_to_collection(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)

    sequences = get_table_queryset(request)
    col_seq = collection.sequences.all()
    sequences = sequences.difference(col_seq)
    context = get_paginated_context(request, sequences)

    if request.method == 'POST':
        if 'add' in request.POST:
            if (request.POST.get('hidden_choice') != '' and request.POST.get('hidden_choice') != None):
                choices = request.POST.get('hidden_choice')
                choices = [int(choice) for choice in choices.split(',')]
                collection.sequences.add(*choices)
            return HttpResponseRedirect(reverse('repo:collection_details', args=(collection.pk,)))

    return render(request, 'repo/collections/add.html', context)


class CollectionDetailsView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Collection
    template_name = 'repo/collections/details.html'
    context_object_name = 'collection'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        name = request.POST.get('name')
        if name:
            self.object.name = name
            self.object.save()

        return self.render_to_response(self.get_context_data(**kwargs))

    def get_context_data(self, **kwargs):
        context = super(CollectionDetailsView, self).get_context_data(**kwargs)
        context = get_table_context_data(context)
        sequences = self.get_object().sequences.all()
        order, filters = get_table_filters(self.request)
        filtered = sequences.filter(**filters).order_by(order)
        paginator = Paginator(filtered, 20)
        page = self.request.GET.get('page')
        context['page_obj'] = paginator.get_page(page)
        return context

    def test_func(self):
        return self.request.user == self.get_object().owner

    def handle_no_permission(self):
        return redirect_to_login(self.request.GET.get('next', self.request.POST.get('next', reverse('repo:collection_details', args=(self.get_object().pk,)))))


class CollectionDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Collection
    success_url = reverse_lazy('repo:collections')
    template_name = 'repo/confirm_delete.html'

    def test_func(self):
        return self.request.user == self.get_object().owner

    def handle_no_permission(self):
        return redirect_to_login(self.request.GET.get('next', self.request.POST.get('next', reverse('repo:collection_delete', args=(self.get_object().pk,)))))


@login_required()
def collection_sequence_delete(request, collection_id, sequence_id):
    sequence = get_object_or_404(ViralSequence, pk=sequence_id)
    collection = get_object_or_404(Collection, pk=collection_id)

    if request.user != collection.owner:
        return redirect_to_login(request.GET.get('next', request.POST.get('next', reverse('repo:collection_sequence_delete', args=(collection.pk, sequence.pk)))))

    if request.method == 'POST':
        collection.sequences.remove(sequence)
        return HttpResponseRedirect(reverse('repo:collection_details', args=(collection_id,)))

    return render(request, 'repo/confirm_delete.html', context={'object': sequence, 'seq_collection': collection})


@login_required()
def download_collection_pdf(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)

    if request.user != collection.owner:
        return redirect_to_login(request.GET.get('next', request.POST.get('next', reverse('repo:download_pdf', args=(collection.pk, )))))

    html_string = render_to_string(
        'repo/collections/pdf.html', {'page_obj': collection.sequences.all()})

    html = HTML(string=html_string)
    html.write_pdf(target='/tmp/' + str(collection.name) + '.pdf')

    fs = FileSystemStorage('/tmp')
    with fs.open(str(collection.name) + '.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="' + \
            str(collection.name) + '.pdf"'
        return response

    return HttpResponseRedirect(reverse('repo:collection_details', args=(collection_id,)))


def stats(request):
    country_names = []
    country_count = []
    center_names = []
    center_count = []

    for country in Country.objects.all():
        country_names.append(country.name)
        country_count.append(country.count)

    for center in Center.objects.all():
        center_names.append(center.name)
        center_count.append(center.count)

    context = {
        'country_names': json.dumps(country_names),
        'country_count': json.dumps(country_count),
        'center_names': json.dumps(center_names),
        'center_count': json.dumps(center_count)
    }

    return render(request, 'repo/stats.html', context)

repo/templates/repo/collections/add.html
{% extends "repo/base.html" %}

{% block head %}
<title>Add sequences</title>
<script>
    $(document).ready(function () {
        $("input[name='reset']").click(function() {                        
            if (sessionStorage.choices) {
                sessionStorage.removeItem('choices');
            }
        });
        $("input[name='add']").click(function() {                        
            if (sessionStorage.choices) {
                sessionStorage.removeItem('choices');
            }
        });
    });
</script>
{% endblock %}

{% block content %}

<p class="lead mt-2">Select your samples. When you are ready Add them.</p>
<form method="POST">
    {% csrf_token %}
    <div class="row mt-4 mb-2">
        <div class="col d-flex justify-content-start form-group">
        </div>
        <div class="col d-flex justify-content-end form-group">
            <input type="submit" class="btn btn-primary" name="add"
                value="Add" />
            <input type="submit" class="btn btn-danger" name="reset"
                value="Reset" />
        </div>
    </div>
    <div class="mb-4">
        {% include "repo/table/body_create.html" %}
        {% include "repo/table/navigation.html" %}
    </div>
</form>
{% include "repo/table/filters.html" %}
{% endblock %}

repo/templates/repo/collections/collections_table.html
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col"><span class="text-dark btn">Collection
                        name</span></th>
                <th scope="col"><span class="text-dark btn">Creation
                        date</span></th>
                <th scope="col"><span class="text-dark btn">View/Edit</span></th>
                <th scope="col"><span class="text-dark btn">Delete</span></th>
            </tr>
        </thead>
        <tbody>
            {% for collection in collections %}
            <tr>
                <th>{{ collection.name }}</th>
                <th>{{ collection.creation_date }}</th>
                <th><a
                        href="{% url 'repo:collection_details' collection.pk %}"><i
                            class="bi bi-pencil-square"></i></a></th>
                <th><a href="{% url 'repo:collection_delete' collection.pk %}"><i
                            class="bi bi-trash"></i></a></th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

repo/templates/repo/collections/create.html
{% extends "repo/base.html" %}

{% block head %}
<title>Create collection</title>
<script>
    $(document).ready(function () {
        $("input[name='reset']").click(function() {                        
            if (sessionStorage.choices) {
                sessionStorage.removeItem('choices');
            }
        });
        $("input[name='create']").click(function() {                        
            if (sessionStorage.choices) {
                sessionStorage.removeItem('choices');
            }
        });
    });
</script>
{% endblock %}

{% block content %}
<p class="lead mt-2">Select your samples. When you are ready name your
    collection and Create it.</p>
<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="refresh" value="" />
    <div class="row mt-4 mb-2">
        <div class="col d-flex justify-content-start form-group">
        </div>
        <div class="col d-flex justify-content-end form-group">
            <label for="collection_name"
                class="col-form-label col-sm-1">Name</label>
            <input type="text" name="collection_name" class="form-control"
                {% if 'collection_name' in request.session %}value={{ request.session.collection_name }}{% endif %}>
            <input type="submit" class="btn btn-primary" name="create"
                value="Create" />
            <input type="submit" class="btn btn-danger" name="reset"
                value="Reset" />
        </div>
    </div>
    <div class="mb-4">
        {% include "repo/table/body_create.html" %}
        {% include "repo/table/navigation.html" %}
    </div>
</form>
{% include "repo/table/filters.html" %}
{% endblock %}

repo/templates/repo/collections/details.html
{% extends "repo/base.html" %}

{% block head %}
<title>Collection details</title>
{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="row my-2">
        <div class="col-7 form-group d-flex justify-content-start form-group">
            <h3 class="w-100"><input type="text" class="form-control-plaintext"
                    name="name" value="{{ collection.name }}"></h3>
        </div>
        <div
            class="col form-group d-flex align-self-center justify-content-end form-group">
            <input type="submit" class="btn btn-primary" value="Change name" />
            <a class="btn btn-primary"
                href="{% url 'repo:add_to_collection' collection.id %}">Add new
                sequences</a>
            <a class="btn btn-primary"
                href="{% url 'repo:download_pdf' collection.id %}">Download
                pdf</a>
        </div>
    </div>
</form>

{% include "repo/table/body_edit.html" %}
{% include "repo/table/navigation.html" %}
{% include "repo/table/filters.html" %}
{% endblock %}

repo/templates/repo/collections/pdf.html
<head>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
    crossorigin="anonymous">
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
  <script
    src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js">
  </script>
  <meta name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <style>
    @page {
      size: landscape;
      margin: 0in 0.44in 0.2in 0.44in;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"><span class="text-dark btn">Accession</span></th>
            <th scope="col"><span class="text-dark btn">Center</span></th>
            <th scope="col"><span class="text-dark btn">Country</span></th>
            <th scope="col"><span class="text-dark btn">Taxonomy</span></th>
            <th scope="col"><span class="text-dark btn">Collection date</span>
            </th>
            <th scope="col"><span class="text-dark btn">Host</span></th>
            <th scope="col"><span class="text-dark btn">Isolate</span></th>
          </tr>
        </thead>
        <tbody>
          {% for sequence in page_obj %}
          <tr scope="row">
            <th>{{ sequence.accession }}</th>
            <th>{{ sequence.center }}</th>
            <th>{{ sequence.country }}</th>
            <th>{{ sequence.taxonomy }}</th>
            <th>{{ sequence.collection_date }}</th>
            <th>{{ sequence.host }}</th>
            <th>{{ sequence.isolate }}</th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</body>